    name: My First Workflow

    on:
     push:
         branches:
             - main
     workflow_dispatch:

    jobs:
       MyFirstJob:
         runs-on: ubuntu-latest
         steps:
           - run: echo "👋 Hello World!"
           - run: echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
           - run: echo "My secret is ${{ secrets.MY_SECRET_NAME }}."
           - name: Checkout
             uses: actions/checkout@v6.0.2
           - name: List files in the repository_dispatch
             run: |
                echo "The repository({ github.repository }) contains the following 
                files:"
                tree
        Test:
          runs-on: ubuntu-latest
          environment: Test
          needs: MyFirstJob
