    name: My First Workflow

    on:
     push:
         branches:
             - main
     workflow_dispatch:

    jobs:
      first_job:
        name: My first job
        runs-on: ubuntu-latest
        steps:
         - run: |
            echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
            echo "My secret is 🤫 ${{ secrets.MY_SECRET }}."
            echo "Current branch is '${{ github.ref }}'."
         - name: Checkout
           uses: actions/checkout@v4.1.0
         - run: tree
         
      Test:
        runs-on: ubuntu-latest
        environment: Test
        needs: first_job
        steps:
         - run: |
             echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
             sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
             echo "My secret is 🤫 '$sec'."
